site_name: test
site_url: https://kweez01.github.io/ogu-ispras-mkdocs/

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Тёмная тема
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Светлая тема
  features:
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: ru